### ISSUE TITLE
No mqtt message outgoing

### ISSUE THREAD

**Issue by HarterHorst** [romor/enocean-mqtt#1]
Hi, i have a problem with outgoing mqtt messages. Button is recognised, but no mqtt message is generated. 

Any ideas?

### Logfile
2017-06-27 16:31:53,242 INFO: Connected to MQTT broker with result code 0
2017-06-27 16:31:53,243 INFO: SerialCommunicator started
2017-06-27 16:31:53,244 WARNING: Replacing Packet.optional with default value.
2017-06-27 16:31:53,352 INFO: Sending packet
2017-06-27 16:31:53,353 DEBUG: 0x05 ['0x8'] [] OrderedDict()
2017-06-27 16:31:53,455 DEBUG: 0x02 ['0x0', '0xff', '0xb0', '0x72', '0x80'] ['0xa'] OrderedDict()
2017-06-27 16:31:53,456 INFO: got response packet: OK
2017-06-27 16:32:01,299 DEBUG: FE:F9:59:1B->FF:FF:FF:FF (-45 dBm): 0x01 ['0xf6', '0x30', '0xfe', '0xf9', '0x59', '0x1b', '0x30'] ['0x3', '0xff', '0xff', '0xff', '0xff', '0x2d', '0x0'] OrderedDict()
2017-06-27 16:32:01,301 INFO: received: FE:F9:59:1B->FF:FF:FF:FF (-45 dBm): 0x01 ['0xf6', '0x30', '0xfe', '0xf9', '0x59', '0x1b', '0x30'] ['0x3', '0xff', '0xff', '0xff', '0xff', '0x2d', '0x0'] OrderedDict()
2017-06-27 16:32:01,303 INFO: learn request received
2017-06-27 16:32:01,471 DEBUG: FE:F9:59:1B->FF:FF:FF:FF (-45 dBm): 0x01 ['0xf6', '0x0', '0xfe', '0xf9', '0x59', '0x1b', '0x20'] ['0x3', '0xff', '0xff', '0xff', '0xff', '0x2d', '0x0'] OrderedDict()
2017-06-27 16:32:01,473 INFO: received: FE:F9:59:1B->FF:FF:FF:FF (-45 dBm): 0x01 ['0xf6', '0x0', '0xfe', '0xf9', '0x59', '0x1b', '0x20'] ['0x3', '0xff', '0xff', '0xff', '0xff', '0x2d', '0x0'] OrderedDict()
2017-06-27 16:32:01,475 INFO: learn request received
### Config file

`#` the general section defines parameter for the mqtt broker and the enocean interface
[CONFIG]
enocean_port    = /dev/ttyAMA0
log_packets     = 1

mqtt_host       = 192.168.0.2
mqtt_port       = 1883
`#` the prefix is used for the mqtt value names; this is extended by the sensor name
mqtt_prefix     = enocean/
`#` optionally also set mqtt_user and mqtt_pwd

`#` all other sections define the sensors to monitor

[Schalter]
address = 0xFEF9591B
rorg    = 0xF6   # BS1
func    = 0x02
type    = 0x01

**Comment by romor** [comment]
I see two issues:
- the logging shows that all received packets are learn requests. Learn requests are not published on mqtt. See https://github.com/romor/enocean-mqtt/blob/edd0e24/enoceanmqtt/communicator.py#L75
- the defined Schalter has an EEP profile which is not present in the used enocean library. See https://github.com/kipe/enocean/blob/49c32fc/enocean/protocol/EEP.xml. For my own switching actuators I use: rorg = 0xf6, func = 0x02, type = 0x04

**Comment by HarterHorst** [comment]
I clearly missed some important basics regarding the protocol. Do you have a shortcut?

What do I have to do to make my Eltako FT55 sending non-learning requestsel? Any hints and links appreciated.

**Comment by romor** [comment]
I also would not expect that teach-in requests are sent by a switching actuator. Maybe this discussion could also be raised in the enocean library (https://github.com/kipe/enocean), which parses the RF packet.

Details on enocean protocol: http://www.enocean.com/esp

**Comment by ozett** [comment]
hi,
i found the same problem, followed the bug description to the originatin library and issu-discussion.
but i am puzzled.
i did not get it, if there was a solution or only discussion ....
maybe one could post here, if there is a solution to this problem of the etako switch..
thanks

**Comment by ozett** [comment]
i have limited enocean knowledge, just started.
i followed to the lib: https://github.com/kipe/enocean
changed the hardcoded /dev/AMA0 to my usb200 /dev/ttyUSB0 and let it running.
no messages of learning mode

my conclusion: somewho it is working.. 
but why not mqtt messages? 
still a bug? a missing feature? 

the enocean lib seems ok for the entako switch ...

anybody with a hint?

**Comment by romor** [comment]
I think this topic is still open. The [enocean](https://github.com/kipe/enocean) library sets the learn flag as a default and the maintainer will not change this ([#66](https://github.com/kipe/enocean/pull/66)).

This library does not emit mqtt messages on learning requests but only on "normal" messages.

**Comment by ozett** [comment]
maybe one more post to clarify this?

as i trigger the switch with the library-tools, i see some infos about the button-click,
but nothing about the "learing" mode. 

with yout tool using the library, i see something about "learing" mode.
and if if follow the issue on the library-thread, the reasons seems that there is a "profile" missing..

i dont know how to implement such a profile, but maybe that could help`?

**Comment by romor** [comment]
The enocean lib sets the learn bit but does not log this. A new profile will not help.

If you are willing to test this I can add an option to also forward learn requests to mqtt.

**Comment by ozett** [comment]
Yes, please.

if you implement forwarding, than i could test if the button press in the default (learing) state of my eltako ft55-rw (which includes the enocean ptm 215) would be send to mqtt.

that would solve my simple case...: "button-press -> mqtt-message"
😁

**Comment by romor** [comment]
Commit d2dea8e introduces a new config file option `log_learn`. If this is set for a specific sensor, this will also forward learn packets to mqtt.

Please give feedback whether this works for you as I do not own such a device for testing.

**Comment by ozett** [comment]
hey, wonderful. thanks.
i will see if i can test this tomorrwo or on the weekend.
as soon as is have a result, i will report back here.

**Comment by romor** [comment]
I assume this can be closed now.
