### ISSUE TITLE
Cannot find type in EEP

### ISSUE THREAD

**Issue by judzk** [romor/enocean-mqtt#31]
Hey guy, just installed enocean2mqtt, but i have one issue.
My module worked perfectly with jeedom, but i want to go to homeassistant, so i use mqtt now.
<img width="359" alt="image" src="https://user-images.githubusercontent.com/26792639/173618994-dbfb7534-77c2-4cd2-b870-ce4ffcb64d93.png">
But on enocean2mqtt i got that :/
My broker receive info, but just the RSSI.
<img width="760" alt="image" src="https://user-images.githubusercontent.com/26792639/173618831-50c3712b-ca77-4567-9431-257a60c9e53c.png">
Any idea?

**Comment by mak-gitdev** [comment]
enoceanmqtt can be seen as an MQTT wrapper for the Python EnOcean library. It is that library that handles the EnOcean protocol.
For that, it uses an XML file named EEP.xml which contains some supported EEP but not all them.
By default, your module which has the EEP D2-01-12 is not supported.

To support your module, please add the code snippet [here](https://forum.hacf.fr/t/enocean-via-enoceanmqtt/11766/21) under the section `telegram rorg="0xD2" / profiles func="0x01"`of your EEP.xml file.

**Comment by judzk** [comment]
Mieux, je n'ai plus l'erreur mais j'ai pas encore toute les infos qui remonte, je vois sur le bouton qui a été appuyé et la CMD est toujours à 4, quelques soit le bouton que j'appuie
<img width="103" alt="image" src="https://user-images.githubusercontent.com/26792639/173631833-f6756b11-cae5-4fce-ba91-7531607df2bf.png">

**Comment by mak-gitdev** [comment]
Do you have an HACF account ? If so, please let's continue there as your initial issue has been solved here ;)
