### ISSUE TITLE
MQTT topic /switch/R1  -- Button 0 same as RELEASE Code 0

### ISSUE THREAD

**Issue by ozett** [romor/enocean-mqtt#5]
hi,
on the Topic /switch/R1 the Button Number of the pressed button from 4 button-switch is published.
But on RELEASE, it got the same 0 (means Zero) as the button number 0 (means zero).

i cannot trigger anything on a single button number from this topic,
as it confuses the button nummer 0 with a 0 for release.
(i dont want to combine two topics as it would complicate things)

could that be changed?
or am i on the wrong track? another way to get around this?

many thx for help...

![image](https://user-images.githubusercontent.com/5937811/48639445-e8ecbb80-e9d3-11e8-800e-2883944b997c.png)

**Comment by ozett** [comment]
i tried simply to edit the EEP.xml,
but run into an error...this did not work

![image](https://user-images.githubusercontent.com/5937811/48641020-c3ae7c00-e9d8-11e8-83c6-a2fcc739ad58.png)

**Comment by romor** [comment]
The EnOcean message profile descriptions are documented [here](https://www.enocean-alliance.org/wp-content/uploads/2018/02/EEP268_R3_Feb022018_public.pdf). You may need to study it to understand the messages.

The interpretation of the EnOcean messages is done by the used [EnOcean library](/kipe/enocean). For such topics you better raise the questions there.

**Comment by ozett** [comment]
thanks for reply,
i had a (simply) quick lock at both sources, 
i think the actual behavior is pretty enocean standard and ok. 

what helped me would be to habe just one mqtt-topic, on which i can trigger actions if button pressed.
as enocean-mqtt is coded i think: actually i would have to combine programmatically two topics to identify a bressed button, which could raise some more problems at another place.

to say it another way: it could be helpful to have a MQTT payload or topic, 
on which one could clear identify with a single message if a button is pressed.

this mapping/topic seems to me could come from enocean-mqtt,
because i seems to be a design-question how mqtt-messages a generated an send from the enocean-standard and underlying libs..

what do you thing?

**Comment by romor** [comment]
Subject of the enocean-mqtt library is to forward EnOcean packets to mqtt and vice versa.

While I understand your problem and request, I do not think that it is a good approach to implement device specific adaptations in a generic library. Probably you could adapt/derive it to extend such custom behaviour.
